


CREATE TABLE Perfil(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(40) NOT NULL
);


CREATE TABLE Usuario(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(40) NOT NULL,
correo_electronico VARCHAR(100) UNIQUE NOT NULL,
contrasena VARCHAR(255) NOT NULL,
perfiles BIGINT NOT NULL,
FOREIGN KEY (perfiles) REFERENCES Perfil(id)
);


CREATE TABLE Curso(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(200) NOT NULL,
categoria VARCHAR(100) NOT NULL
);

CREATE TABLE Topico(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(255) NOT NULL,
mensaje TEXT NOT NULL,
fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
status VARCHAR(20) DEFAULT  'ACTIVO',
autor BIGINT NOT NULL,
curso BIGINT NOT NULL,
respuestas INT DEFAULT 0,
FOREIGN KEY (autor) REFERENCES Usuario(id),
FOREIGN KEY (curso) REFERENCES Curso(id)
);

CREATE TABLE Respuesta(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
mensaje TEXT NOT NULL,
topico BIGINT NOT NULL,
fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
autor BIGINT NOT NULL,
solucion BOOLEAN DEFAULT FALSE,
FOREIGN KEY (topico) REFERENCES Topico(id),
FOREIGN KEY (autor) REFERENCES Usuario(id)
);
